### ISSUE TITLE
你好, 有个bug, 感谢

### ISSUE THREAD

**Issue by zhangenming** [tropicalwzc/ice_sudoku.github.io#1]
点分布解释 -> 点撤回 ->再点分布解释
这时候分布解释没有撤回 是继续按照第一次的分布解释继续解释的(有时候是)

**Comment by tropicalwzc** [comment]
Windows版本吗

**Comment by zhangenming** [comment]
> Windows版本吗

嗯 忘了说
另外提个小需求
点到某数字时最好也高亮下 不确定格里可能的数字
类似这种 
![image](https://user-images.githubusercontent.com/21235555/85923381-03c82700-b8bd-11ea-9eba-ba3130b58d31.png)

另外自动生成数独是怎么做的  谢谢

**Comment by tropicalwzc** [comment]
可以了，更新到1.2.3版本就行了
![屏幕截图(81)](https://user-images.githubusercontent.com/31509619/86509311-8ef37080-be19-11ea-9f89-079c44576b32.png)
